const actor = {
  "id": 3783,
  "type": "Actor",
  "user_id": 342,
  "short_description": "Mit Schulklassen setzen wir Suffizienz- und Postwachstumsideen um: Es geht um Gl\u00fcck\/Lebensstandard, Permakultur\/G\u00e4rtnern, Klima\/Alltagshandeln.",
  "service_type": "Projekt",
  "name": "Natur.Raum.Gestalten",
  "description": "Im Projekt Natur.Raum.Gestalten, das vom barfu\u00df e.V. im Rahmen des ESF-gef\u00f6rderten Projekts noPlanetB entworfen wurde, werden an 3 Projekttagen mit Schulklassen Suffizienz- und Postwachstumsideen vermittelt:\r\n\r\n1) Gl\u00fcck und Lebensstandard - Quellen von Gl\u00fcck. Mein Gl\u00fcck und meine Umwelt.\r\n2) Permakultur - Naturerfahrung und nachhaltiges G\u00e4rtnern als Klimaschutz\r\n3) Klima und Alltag - Klimafolgen, Klimagerechtigkeit und Handlungsoptionen\r\n\r\nDie Projekttage werden teils an den Schulen, teils im Outdoor Camp Trampelpfad des barfu\u00df e.V. bei Eilenburg umgesetzt. \r\nIm Anschluss an die Projekttage mit den Schulklassen findet eine Multiplikator*innen-Veranstaltung statt.\r\n\r\nIn Modul 1 besch\u00e4ftigen wir uns mithilfe kreativer Methoden mit unseren Quellen von Gl\u00fcck und hinterfragen den Zusammenhang von Lebensstandard und Gl\u00fcck sowie Auswirkungen auf die Umwelt. Dazu erz\u00e4hlen wir eine Geschichte, spielen Szenen daraus nach und erstellen eine Collage zu unseren Gl\u00fccksfaktoren.\r\n\r\nIn Modul 2 wenden wir Methoden der regenerativen Landgestaltung (Permakultur) an, wie Bodenpflege als Ma\u00dfnahme zum Klimaschutz und zum Erhalt nat\u00fcrlicher Lebensgrundlagen. Dabei wird die Begrenzung nat\u00fcrlicher Wachstumsprozesse ebenso deutlich wie die Bedeutung nachhaltiger Ressourcennutzung. Wir gestalten gemeinsam ein Permakultur-Element, indem wir z.B. ein Wildholzsofa bauen und bepflanzen.\r\n\r\nIn Modul 3 geht es um den \"\u00f6kologischen Fu\u00dfabdruck\" sowie Klimafolgen und Klimagerechtigkeit. Die Sch\u00fcler*innen k\u00f6nnen die Auswirkungen unseres Handelns im globalen Norden an konkreten Beispielen aus dem globalen S\u00fcden erkennen. Wir erproben Handlungsoptionen f\u00fcr den Alltag. Dazu setzen wir Beispiele aus den Bereichen regional-saisonale Ern\u00e4hrung, Upcycling und F\u00f6rderung von Biodiversit\u00e4t um. Als Abschluss gibt es klimafreundliches Picknick, zu dem auch die Eltern der Sch\u00fcler*innen eingeladen sind.\r\n\r\nIn einer Veranstaltung f\u00fcr Multiplikator*innen werden die Projektmaterialien weitergereicht und es wird fachlicher Austausch unter Akteur*innen der Bildung f\u00fcr nachhaltige Entwicklung (BNE) aus der Region Leipzig \/ D\u00fcbener Heide erm\u00f6glicht.",
  "location_id": 377,
  "full_address": "Lindenallee 15, 04838  Dobersch\u00fctz OT Sprotta",
  "is_fallback_address": false,
  "street_name": "Lindenallee 15",
  "house_number": "15",
  "zip": "04838",
  "city": " Dobersch\u00fctz OT Sprotta",
  "latlng": [51.528734, 12.599276],
  "district": null,
  "info_url": "https:\/\/www.barfuss-ev.de\/naturraumgestalten",
  "video_url": "",
  "image_url": "https:\/\/daten.nachhaltiges-sachsen.de\/api\/v1\/images\/3412\/Projektbild_Natur.Raum.Gestalten_klein.JPG",
  "image_url_base": "https:\/\/daten.nachhaltiges-sachsen.de\/media\/3412\/Projektbild_Natur.Raum.Gestalten_klein.JPG",
  "published": true,
  "start_at": null,
  "end_at": null,
  "duration": null,
  "costs": null,
  "requirements": null,
  "speaker": null,
  "curriculum": null,
  "property_list": ["- Methoden: kreativ, handlungsorientiert\r", "- Herangehensweise: ergebnissoffen, prozessorientiert\r", "- Zielgruppe: Grundsch\u00fcler*innen und deren Eltern sowie Multiplikator*innen\r", "- Ort: l\u00e4ndlicher Raum\r", "- Setting: im Freien und an Schulen"],
  "free": false,
  "child_friendly": false,
  "accessible": false,
  "climate_protection": false,
  "region": {"id": 109, "name": "Landkreis Nordsachsen"},
  "categories": [12, 9, 24, 5, 18, 7],
  "first_root_category": 9,
  "root_categories": [9, 5, 7],
  "goals": ["Boden und Grundwasser sch\u00fctzen", "Handlungskompetenz erwerben", "nachaltiger Lebensstil", "Naturraum sch\u00fctzen"],
  "target_group_selection": null,
  "target_group": null,
  "education_type": null,
  "products": [],
  "trade_categories": [],
  "trade_types": []
}

module.exports = actor
